
$schema: '/Users/thim/Sites/portman/src/utils/portman-config-schema.json'
version: 1
tests:
  contractTests:
    - openApiOperation: "*::/*"
      statusSuccess:
        enabled: true
    - openApiOperation: "*::/*"
      responseTime:
        enabled: false
        maxMs: 5
    - openApiOperation: "*::/*"
      contentType:
        enabled: true
    - openApiOperation: "*::/*"
      jsonBody:
        enabled: true
    - openApiOperation: "*::/*"
      schemaValidation:
        enabled: true
    - openApiOperation: "*::/*"
      headersPresent:
        enabled: true
  contentTests: [ ]
assignVariables:
  - openApiOperation: POST::*
    collectionVariables:
      - responseBodyProp: id
        name: <tag>Id
  - openApiOperation: GET::*
    excludeForOperations:
      - "GET::/*/{id}"
    collectionVariables:
      - responseBodyProp: <tag>[0].id
        name: <tag>Id
overwrites:
  - openApiOperation: "*::/*/{id}"
    overwriteRequestPathVariables:
      - key: id
        value: '{{<tag>Id}}'
        overwrite: true
globals:
  stripResponseExamples: true
  variableCasing: camelCase
#  securityOverwrites:
#    bearer:
#      token: "{{bearerToken}}"
